### ISSUE TITLE
Custom language or text corpus

### ISSUE THREAD

**Issue by duraki** [watzon/cadmium#11]

**Comment by watzon** [comment]
@duraki could you provide more information and context?

**Comment by duraki** [comment]
@watzon yes, as per README, the project currently supports:
  
> The aggressive tokenizer currently has localization available for English (:en / nil), Spanish (:es), Persian (:fa), French (:fr), Indonesian (:id), Dutch (:nl), Norwegian (:no), Polish (:pl), Portuguese (:pt), Russian (:ru), and Swedish (:sv)
  
How should we go about adding an Indo-European [slavic](https://en.wikipedia.org/wiki/Slavic_languages) languages, for example: Serbian, Croatian or Bosnian?

**Comment by watzon** [comment]
@duraki well you'd need to add a section to [this](https://github.com/watzon/cadmium/blob/master/src/cadmium/tokenizer/aggressive_tokenizer.cr) file for each language that you want supported. I imagine most of the languages you mentioned have similar, if not the same rules when it comes to what characters can make up a word, so it shouldn't be too difficult.

If you want to open a PR I'd be more than happy to merge it.

I also have planned support for Russian, Slovak, Czech, and Bulgarian for the `PragmaticTokenizer`

**Comment by watzon** [comment]
This should be fixed with 1df4efe. For now I've bundled support for slavic languages such as russian, serbian, and ukrianian together. Let me know if this does not work correctly.
