### ISSUE TITLE
Moving all cadmiumcr/rfcs issues to cadmiumcr/cadmium (ie here)

### ISSUE THREAD

**Issue by rmarronnier** [watzon/cadmium#30]
As all cadmium shards have their own repo, there is no point for users to open issues here, unless it's for new proposals which are not covered by existing shards, which cadmiumcr/rfcs is about.

IMO, it would be more obvious to move all rfcs/proposals here and close cadmium/rfcs.

We should also move your templates (very useful) here.

@watzon : WDYT ?

**Comment by watzon** [comment]
I agree actually, let's do that

**Comment by rmarronnier** [comment]
You rock man, thanks for acting so fast :fist_oncoming:

**Comment by watzon** [comment]
No problem. Thanks for all the work you've been doing here. I'm gonna start getting back into this project soon. Maybe try and figure out how to consolidate the docs.

**Comment by watzon** [comment]
They've been transferred. I'll close cadmium/rfcs

**Comment by rmarronnier** [comment]
> No problem. Thanks for all the work you've been doing here. I'm gonna start getting back into this project soon. Maybe try and figure out how to consolidate the docs.

Good luck with the docs, I tried to make `crystal spec` work on the gathered shards for a few hours and faced so many issues/conflicts... And finally gave up :-/

> They've been transferred. I'll close cadmium/rfcs

Thanks for that. Actually `rfcs` is still opened, I can't close it, I don't have the rights on it.

**Comment by watzon** [comment]
Ahh yeah I'll shut it down
