### ISSUE TITLE
Website links out to date

### ISSUE THREAD

**Issue by Calamari** [watzon/cadmium#35]
Just let you know that the links under "Content" are a bit out to date. They link to https://github.com/cadmiumcr/cadmium#stemmers for example, but there is no `#stemmers` headline, You probable meant to let it link to https://github.com/cadmiumcr/stemmer?

This is like that for all those links.

**Comment by watzon** [comment]
Yeah it hasn't been updated since the repo got split into multiple. I'll fix it soon. Thanks :)

**Comment by Calamari** [comment]
Cool :)
Like that project btw :D

**Comment by watzon** [comment]
Fixed! Thanks :)
