### ISSUE TITLE
Add Word2Vec

### ISSUE THREAD

**Issue by watzon** [watzon/cadmium#5]
Word2Vec is an algorithm created by Google to compare words or phrases by assigning each individual word its own position in vector space. Words are moved around according to how similar they are to other words, creating a graph of words and their similarity to other words.

**Comment by alexanderadam** [comment]
This would be awesome!

Maybe [`word2vec-ruby`](https://github.com/mnarayan01/word2vec-ruby) or [`RubyWordToVec`](https://github.com/anhad13/RubyWordToVec) might help as an inspiration.

Also keep in mind that [the 'official' implementation doesn't seem to be flawless](http://bollu.github.io/#everything-you-know-about-word2vec-is-wrong).

**Comment by watzon** [comment]
I've taken a look at the Ruby implementations, but they use a lot of metaprogramming that doesn't translate well to crystal. I've actually been working on an implementation of GLOVE which I've gotten very close.

**Comment by alexanderadam** [comment]
> I've actually been working on an implementation of GLOVE which I've gotten very close.

Awesome! :tada:

**Comment by rmarronnier** [comment]
@watzon : Do you want to close this issue ? Unless you want to add word2vec to cadmium along with your GLove implementation (seems overkill to me ;-))

**Comment by watzon** [comment]
:ok_hand:
